py_library(
    name = "total_cell",
    srcs = ["total_cell.py"],
    deps = [
        ":base_returning_info",
    ]
)

py_library(
    name = "base_returning_info",
    srcs = ["base_returning_info.py"],
    visibility = ["//visibility:public"],
)
